### ISSUE TITLE
Problame SMTP

### ISSUE THREAD

**Issue by DemOnJR** [IonutPopescuRO/Metin2CMS#2]
Am descarcat cms-ul default si am adaugat detaliile serverului smtp exact cum sunt in cpanel si apare aceasta eroare:
![image](https://user-images.githubusercontent.com/6385558/99096686-df07ee00-25d6-11eb-8694-4c1b50d1f248.png)

**Comment by IonutPopescuRO** [comment]
Salut, pentru a vedea eroarea completă mergi în **include/functions/sendEmail.php** și setează valoarea 3 la SMTPDebug:
`$mail->SMTPDebug  = 3;`

**Comment by DemOnJR** [comment]
am rezolvat, gazduirejocuri avea probleme cu smtp dar am refacut webhost-ul si este ok.
