### ISSUE TITLE
Uncaught Error: Call to a member function prepare() on null

### ISSUE THREAD

**Issue by Mangodzilla** [IonutPopescuRO/Metin2CMS#3]
Greetings!

I was trying to install CMS on my web server; 
Php 7.3 is installed and php7.3-mysql package is installed (includes pdo).
Using an own-made php script for testing purposes, I managed to create new users on the database to test that the connection can be made without problems.

I've then installed CMS by editing the config.php file properly, using valid credentials.

I'm getting "Server is offline" even if both the server and the database are actually online.
In the apache errorlog i'm getting an error referring to the function prepare() that appears to be broke.

`PHP Fatal error:  Uncaught Error: Call to a member function prepare() on null in /var/www/html/aaa/include/classes/news.php:119\nStack trace:\n#0 /var/www/html/aaa/pages/news.php(29): paginate->dataview('SELECT * FROM n...', 'Are you sure?', 0, 9, 'http://bbb.cc...', 'Read more')\n#1 /var/www/html/aaa/index.php(94): include('/var/www/html/a...')\n#2 {main}\n  thrown in /var/www/html/aaa/include/classes/news.php on line 119, referer: http://bbb.ccc/aaa/`

Sure that I'm missing something stupid, can't figure out what.

Thanks in advance for this brilliant work!

Cheers

**Comment by IonutPopescuRO** [comment]
This is a server issue.
